# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('negative_polarity', models.FloatField(default=0.0)),
                ('positive_polarity', models.FloatField(default=0.0)),
                ('neutral_polarity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=140)),
                ('tweet_polarity', models.CharField(max_length=10)),
            ],
        ),
    ]
