# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_selections_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selections',
            name='person_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='person_id', to='sentiment.Person'),
        ),
    ]
